package com.jpaver.trianglelist.writer

import java.io.BufferedWriter

class DxfHeader(private val handles: HandleGen) {

    fun header(writer: BufferedWriter, paper: Paper, printScale: PrintScale){
        // Reserve first handle value so that $HANDSEED points **after** the highest in-use
        // handle.  DXF spec: "$HANDSEED shall contain a handle that is greater than any
        // handle currently in the database."  We consume one handle here to avoid duplicating
        // the very first real object handle (often 40) that gets assigned in TABLES.
        val reservedForSeed = handles.new()

        // Calculate scale factor for DIMSCALE (typically 1/50 = 50.0)
        val scaleForDimScale = printScale.paper / printScale.model
        // EXTMAX should reflect actual model space content, but limited to reasonable size
        // Use paper size * scale factor, but cap at reasonable maximum
        val modelSpaceX = paper.width * scaleForDimScale
        val modelSpaceY = paper.height * scaleForDimScale
        val extMaxX = minOf(modelSpaceX, paper.width * 100) // Cap at 100x paper size
        val extMaxY = minOf(modelSpaceY, paper.height * 100)

        // ログ出力：計算値を確認（テスト時は出力しない）
        try {
            android.util.Log.d("DxfHeader", "=== DXFヘッダー計算値 ===")
            android.util.Log.d("DxfHeader", "reservedForSeed: $reservedForSeed")
            android.util.Log.d("DxfHeader", "scaleForDimScale: $scaleForDimScale (${printScale.paper}/${printScale.model})")
            android.util.Log.d("DxfHeader", "extMaxX: $extMaxX (${paper.width} * $scaleForDimScale)")
            android.util.Log.d("DxfHeader", "extMaxY: $extMaxY (${paper.height} * $scaleForDimScale)")
            android.util.Log.d("DxfHeader", "PEXTMAX: ${paper.width} x ${paper.height}")
        } catch (e: Exception) {
            // ユニットテスト環境では標準出力に出力
            println("=== DXFヘッダー計算値 ===")
            println("reservedForSeed: $reservedForSeed")
            println("scaleForDimScale: $scaleForDimScale (${printScale.paper}/${printScale.model})")
            println("extMaxX: $extMaxX (${paper.width} * $scaleForDimScale)")
            println("extMaxY: $extMaxY (${paper.height} * $scaleForDimScale)")
            println("PEXTMAX: ${paper.width} x ${paper.height}")
        }
        try {
            android.util.Log.d("DxfHeader", "LIMMAX: ${extMaxX*1.2} x ${extMaxY*1.2}")
        } catch (e: Exception) {
            println("LIMMAX: ${extMaxX*1.2} x ${extMaxY*1.2}")
        }

        writer.write("""
             0
            SECTION
              2
            HEADER
              9
            ${'$'}ACADVER
              1
            AC1015
              9
            ${'$'}INSUNITS
             70
              6             ; ミリメートル
              9
            ${'$'}ACADMAINTVER
             70
                20
              9
            ${'$'}DWGCODEPAGE
              3
            ANSI_932
              9
            ${'$'}INSBASE
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}EXTMIN
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}EXTMAX
             10
            $extMaxX
             20
            $extMaxY
             30
            0.0
              9
            ${'$'}PEXTMAX
             10
            ${paper.width}
             20
            ${paper.height}
             30
            0.0
            9
            ${'$'}LIMMIN
            10
            0.0
            20
            0.0
            9
            ${'$'}LIMMAX
            10
            ${extMaxX}
            20
            ${extMaxY}
            9
            ${'$'}ORTHOMODE
             70
                 0
              9
            ${'$'}REGENMODE
             70
                 1
              9
            ${'$'}FILLMODE
             70
                 1
              9
            ${'$'}QTEXTMODE
             70
                 0
              9
            ${'$'}MIRRTEXT
             70
                 0
              9
            ${'$'}LTSCALE
             40
            1.0
              9
            ${'$'}ATTMODE
             70
                 1
              9
            ${'$'}TEXTSIZE
             40
            0.2
              9
            ${'$'}TRACEWID
             40
            0.05
              9
            ${'$'}TEXTSTYLE
              7
            DIMSTANDARD
              9
            ${'$'}CLAYER
              8
            0
              9
            ${'$'}CELTYPE
              6
            Continuous
              9
            ${'$'}CECOLOR
             62
               256
              9
            ${'$'}CELTSCALE
             40
            1.0
              9
            ${'$'}DISPSILH
             70
                 0
              9
            ${'$'}DIMSCALE
             40
            $scaleForDimScale
              9
            ${'$'}DIMASZ
             40
            0.18
              9
            ${'$'}DIMEXO
             40
            0.0625
              9
            ${'$'}DIMDLI
             40
            0.38
              9
            ${'$'}DIMRND
             40
            0.0
              9
            ${'$'}DIMDLE
             40
            0.0
              9
            ${'$'}DIMEXE
             40
            0.18
              9
            ${'$'}DIMTP
             40
            0.0
              9
            ${'$'}DIMTM
             40
            0.0
              9
            ${'$'}DIMTXT
             40
            0.18
              9
            ${'$'}DIMCEN
             40
            0.09
              9
            ${'$'}DIMTSZ
             40
            0.0
              9
            ${'$'}DIMTOL
             70
                 0
              9
            ${'$'}DIMLIM
             70
                 0
              9
            ${'$'}DIMTIH
             70
                 1
              9
            ${'$'}DIMTOH
             70
                 1
              9
            ${'$'}DIMSE1
             70
                 0
              9
            ${'$'}DIMSE2
             70
                 0
              9
            ${'$'}DIMTAD
             70
                 0
              9
            ${'$'}DIMZIN
             70
                 0
              9
            ${'$'}DIMBLK
              1
            
              9
            ${'$'}DIMASO
             70
                 1
              9
            ${'$'}DIMSHO
             70
                 1
              9
            ${'$'}DIMPOST
              1
            
              9
            ${'$'}DIMAPOST
              1
            
              9
            ${'$'}DIMALT
             70
                 0
              9
            ${'$'}DIMALTD
             70
                 2
              9
            ${'$'}DIMALTF
             40
            25.4
              9
            ${'$'}DIMLFAC
             40
            1.0
              9
            ${'$'}DIMTOFL
             70
                 0
              9
            ${'$'}DIMTVP
             40
            0.0
              9
            ${'$'}DIMTIX
             70
                 0
              9
            ${'$'}DIMSOXD
             70
                 0
              9
            ${'$'}DIMSAH
             70
                 0
              9
            ${'$'}DIMBLK1
              1
            
              9
            ${'$'}DIMBLK2
              1
            
              9
            ${'$'}DIMSTYLE
              2
            Standard
              9
            ${'$'}DIMCLRD
             70
                 0
              9
            ${'$'}DIMCLRE
             70
                 0
              9
            ${'$'}DIMCLRT
             70
                 0
              9
            ${'$'}DIMTFAC
             40
            1.0
              9
            ${'$'}DIMGAP
             40
            0.09
              9
            ${'$'}DIMJUST
             70
                 0
              9
            ${'$'}DIMSD1
             70
                 0
              9
            ${'$'}DIMSD2
             70
                 0
              9
            ${'$'}DIMTOLJ
             70
                 1
              9
            ${'$'}DIMTZIN
             70
                 0
              9
            ${'$'}DIMALTZ
             70
                 0
              9
            ${'$'}DIMALTTZ
             70
                 0
              9
            ${'$'}DIMUPT
             70
                 0
              9
            ${'$'}DIMDEC
             70
                 4
              9
            ${'$'}DIMTDEC
             70
                 4
              9
            ${'$'}DIMALTU
             70
                 2
              9
            ${'$'}DIMALTTD
             70
                 2
              9
            ${'$'}DIMTXSTY
              7
            Standard
              9
            ${'$'}DIMAUNIT
             70
                 0
              9
            ${'$'}DIMADEC
             70
                 0
              9
            ${'$'}DIMALTRND
             40
            0.0
              9
            ${'$'}DIMAZIN
             70
                 0
              9
            ${'$'}DIMDSEP
             70
                46
              9
            ${'$'}DIMATFIT
             70
                 3
              9
            ${'$'}DIMFRAC
             70
                 0
              9
            ${'$'}DIMLDRBLK
              1
            
              9
            ${'$'}DIMLUNIT
             70
                 2
              9
            ${'$'}DIMLWD
             70
                -2
              9
            ${'$'}DIMLWE
             70
                -2
              9
            ${'$'}DIMTMOVE
             70
                 0
              9
            ${'$'}LUNITS
             70
                 2
              9
            ${'$'}LUPREC
             70
                 4
              9
            ${'$'}SKETCHINC
             40
            0.1
              9
            ${'$'}FILLETRAD
             40
            0.0
              9
            ${'$'}AUNITS
             70
                 0
              9
            ${'$'}AUPREC
             70
                 0
              9
            ${'$'}MENU
              1
            .
              9
            ${'$'}ELEVATION
             40
            0.0
              9
            ${'$'}PELEVATION
             40
            0.0
              9
            ${'$'}THICKNESS
             40
            0.0
              9
            ${'$'}LIMCHECK
             70
                 0
              9
            ${'$'}CHAMFERA
             40
            0.0
              9
            ${'$'}CHAMFERB
             40
            0.0
              9
            ${'$'}CHAMFERC
             40
            0.0
              9
            ${'$'}CHAMFERD
             40
            0.0
              9
            ${'$'}SKPOLY
             70
                 0
              9
            ${'$'}TDCREATE
             40
            2459198.769561898
              9
            ${'$'}TDUCREATE
             40
            2459198.394561898
              9
            ${'$'}TDUPDATE
             40
            2459198.771185336
              9
            ${'$'}TDUUPDATE
             40
            2459198.396185336
              9
            ${'$'}TDINDWG
             40
            0.0014492593
              9
            ${'$'}TDUSRTIMER
             40
            0.0014490856
              9
            ${'$'}USRTIMER
             70
                 1
              9
            ${'$'}ANGBASE
             50
            0.0
              9
            ${'$'}ANGDIR
             70
                 0
              9
            ${'$'}PDMODE
             70
                 0
              9
            ${'$'}PDSIZE
             40
            0.0
              9
            ${'$'}PLINEWID
             40
            0.0
              9
            ${'$'}SPLFRAME
             70
                 0
              9
            ${'$'}SPLINETYPE
             70
                 6
              9
            ${'$'}SPLINESEGS
             70
                 8
              9
            ${'$'}HANDSEED
              5
            ${handles.current()}
              9
            ${'$'}SURFTAB1
             70
                 6
              9
            ${'$'}SURFTAB2
             70
                 6
              9
            ${'$'}SURFTYPE
             70
                 6
              9
            ${'$'}SURFU
             70
                 6
              9
            ${'$'}SURFV
             70
                 6
              9
            ${'$'}UCSBASE
              2
            
              9
            ${'$'}UCSNAME
              2
            
              9
            ${'$'}UCSORG
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSXDIR
             10
            1.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSYDIR
             10
            0.0
             20
            1.0
             30
            0.0
              9
            ${'$'}UCSORTHOREF
              2
            
              9
            ${'$'}UCSORTHOVIEW
             70
                 0
              9
            ${'$'}UCSORGTOP
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSORGBOTTOM
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSORGLEFT
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSORGRIGHT
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSORGFRONT
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSORGBACK
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSBASE
              2
            
              9
            ${'$'}PUCSNAME
              2
            
              9
            ${'$'}PUCSORG
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSXDIR
             10
            1.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSYDIR
             10
            0.0
             20
            1.0
             30
            0.0
              9
            ${'$'}PUCSORTHOREF
              2
            
              9
            ${'$'}PUCSORTHOVIEW
             70
                 0
              9
            ${'$'}PUCSORGTOP
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSORGBOTTOM
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSORGLEFT
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSORGRIGHT
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSORGFRONT
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSORGBACK
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}USERI1
             70
                 0
              9
            ${'$'}USERI2
             70
                 0
              9
            ${'$'}USERI3
             70
                 0
              9
            ${'$'}USERI4
             70
                 0
              9
            ${'$'}USERI5
             70
                 0
              9
            ${'$'}USERR1
             40
            0.0
              9
            ${'$'}USERR2
             40
            0.0
              9
            ${'$'}USERR3
             40
            0.0
              9
            ${'$'}USERR4
             40
            0.0
              9
            ${'$'}USERR5
             40
            0.0
              9
            ${'$'}WORLDVIEW
             70
                 1
              9
            ${'$'}SHADEDGE
             70
                 3
              9
            ${'$'}SHADEDIF
             70
                70
              9
            ${'$'}TILEMODE
             70
                 1
              9
            ${'$'}MAXACTVP
             70
                64
              9
            ${'$'}PINSBASE
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PLIMCHECK
             70
                 0
              9
            ${'$'}PEXTMIN
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PEXTMAX
             10
            ${paper.width}
             20
            ${paper.height}
             30
            0.0
              9
            ${'$'}PLIMMIN
             10
            0.0
             20
            0.0
              9
            ${'$'}PLIMMAX
             10
            ${paper.width}
             20
            ${paper.height}
              9
            ${'$'}UNITMODE
             70
                 0
              9
            ${'$'}VISRETAIN
             70
                 1
              9
            ${'$'}PLINEGEN
             70
                 0
              9
            ${'$'}PSLTSCALE
             70
                 1
              9
            ${'$'}TREEDEPTH
             70
              3020
              9
            ${'$'}CMLSTYLE
              2
            Standard
              9
            ${'$'}CMLJUST
             70
                 0
              9
            ${'$'}CMLSCALE
             40
            1.0
              9
            ${'$'}PROXYGRAPHICS
             70
                 1
              9
            ${'$'}MEASUREMENT
             70
                 0
              9
            ${'$'}CELWEIGHT
            370
                -1
              9
            ${'$'}ENDCAPS
            280
                 0
              9
            ${'$'}JOINSTYLE
            280
                 0
              9
            ${'$'}LWDISPLAY
            290
                 0
              9
            ${'$'}HYPERLINKBASE
              1
            
              9
            ${'$'}STYLESHEET
              1
            
              9
            ${'$'}XEDIT
            290
                 1
              9
            ${'$'}CEPSNTYPE
            380
                 0
              9
            ${'$'}PSTYLEMODE
            290
                 1
              9
            ${'$'}FINGERPRINTGUID
              2
            {68315CFD-F49C-40F0-8814-45FE33FC9483}
              9
            ${'$'}VERSIONGUID
              2
            {D8A8B553-77FB-4109-8835-302D291E56A1}
              9
            ${'$'}EXTNAMES
            290
                 1
              9
            ${'$'}PSVPSCALE
             40
            0.0
              9
            ${'$'}OLESTARTUP
            290
                 0
            0
            ENDSEC
        """.trimIndent())
        writer.newLine()
    }

}