package com.jpaver.trianglelist.datamanager

import java.io.BufferedWriter

class DxfObject {

    fun dxfobject(writer:BufferedWriter){
        writer.write("""
              0
            SECTION
              2
            OBJECTS
              0
            DICTIONARY
              5
            C
            330
            0
            100
            AcDbDictionary
            281
                 1
              3
            ACAD_COLOR
            350
            2F
              3
            ACAD_GROUP
            350
            D
              3
            ACAD_LAYOUT
            350
            2E
              3
            ACAD_MATERIAL
            350
            10
              3
            ACAD_MLINESTYLE
            350
            2B
              3
            ACAD_PLOTSETTINGS
            350
            2D
              3
            ACAD_PLOTSTYLENAME
            350
            E
              3
            ACAD_TABLESTYLE
            350
            30
              3
            ACAD_VISUALSTYLE
            350
            14
              3
            AcDbVariableDictionary
            350
            6A
              3
            DWGPROPS
            350
            81
              0
            DICTIONARY
              5
            2F
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              0
            DICTIONARY
              5
            D
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              0
            DICTIONARY
              5
            2E
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            Model
            350
            39
              3
            レイアウト1
            350
            35
              0
            DICTIONARY
              5
            10
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            ByBlock
            350
            12
              3
            ByLayer
            350
            11
              3
            Global
            350
            13
              0
            DICTIONARY
              5
            2B
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            Standard
            350
            2C
              0
            DICTIONARY
              5
            2D
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              0
            ACDBDICTIONARYWDFLT
              5
            E
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            Normal
            350
            F
            100
            AcDbDictionaryWithDefault
            340
            F
              0
            DICTIONARY
              5
            30
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            Standard
            350
            31
              0
            DICTIONARY
              5
            14
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            2dWireframe
            350
            1A
              3
            3D Hidden
            350
            1C
              3
            3dWireframe
            350
            1B
              3
            Basic
            350
            19
              3
            Brighten
            350
            20
              3
            ColorChange
            350
            24
              3
            Conceptual
            350
            1D
              3
            Dim
            350
            1F
              3
            Facepattern
            350
            23
              3
            Flat
            350
            15
              3
            FlatWithEdges
            350
            16
              3
            Gouraud
            350
            17
              3
            GouraudWithEdges
            350
            18
              3
            Linepattern
            350
            22
              3
            Realistic
            350
            1E
              3
            Thicken
            350
            21
              0
            DICTIONARY
              5
            6A
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            CTABLESTYLE
            350
            6B
              3
            DIMASSOC
            350
            6E
              3
            INDEXCTL
            350
            6D
              3
            SORTENTS
            350
            6C
              0
            XRECORD
              5
            81
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbXrecord
            280
                 1
              1
            DWGPROPS COOKIE
              2
            
              3
            
              4
            
              6
            
              7
            
              8
            三雄
              9
            
            300
            =
            301
            =
            302
            =
            303
            =
            304
            =
            305
            =
            306
            =
            307
            =
            308
            =
            309
            =
             40
            0.0014492592592593
             41
            2459198.769561898
             42
            2459198.771185336
              1
            
             90
                    0
              0
            LAYOUT
              5
            39
            102
            {ACAD_XDICTIONARY
            360
            86
            102
            }
            102
            {ACAD_REACTORS
            330
            2E
            102
            }
            330
            2E
            100
            AcDbPlotSettings
              1
            
              2
            Canon MG6200 series
              4
            
              6
            
             40
            0.0
             41
            0.0
             42
            0.0
             43
            0.0
             44
            0.0
             45
            0.0
             46
            0.0
             47
            0.0
             48
            0.0
             49
            0.0
            140
            0.0
            141
            0.0
            142
            1.0
            143
            1.0
             70
              1712
             72
                 0
             73
                 0
             74
                 0
              7
            
             75
                 0
            147
            1.0
            148
            0.0
            149
            0.0
            100
            AcDbLayout
              1
            Model
             70
                 1
             71
                 0
             10
            0.0
             20
            0.0
             11
            12.0
             21
            9.0
             12
            0.0
             22
            0.0
             32
            0.0
             14
            0.0
             24
            0.0
             34
            0.0
             15
            0.0
             25
            0.0
             35
            0.0
            146
            0.0
             13
            0.0
             23
            0.0
             33
            0.0
             16
            1.0
             26
            0.0
             36
            0.0
             17
            0.0
             27
            1.0
             37
            0.0
             76
                 0
            330
            36
            331
            3A
              0
            LAYOUT
              5
            35
            102
            {ACAD_XDICTIONARY
            360
            84
            102
            }
            102
            {ACAD_REACTORS
            330
            2E
            102
            }
            330
            2E
            100
            AcDbPlotSettings
              1
            
              2
            Canon MG6200 series
              4
            
              6
            
             40
            0.0
             41
            0.0
             42
            0.0
             43
            0.0
             44
            0.0
             45
            0.0
             46
            0.0
             47
            0.0
             48
            0.0
             49
            0.0
            140
            0.0
            141
            0.0
            142
            1.0
            143
            1.0
             70
               688
             72
                 0
             73
                 0
             74
                 5
              7
            
             75
                16
            147
            1.0
            148
            0.0
            149
            0.0
            100
            AcDbLayout
              1
            レイアウト1
             70
                 1
             71
                 1
             10
            0.0
             20
            0.0
             11
            12.0
             21
            9.0
             12
            0.0
             22
            0.0
             32
            0.0
             14
            1.000000000000000E+20
             24
            1.000000000000000E+20
             34
            1.000000000000000E+20
             15
            -1.000000000000000E+20
             25
            -1.000000000000000E+20
             35
            -1.000000000000000E+20
            146
            0.0
             13
            0.0
             23
            0.0
             33
            0.0
             16
            1.0
             26
            0.0
             36
            0.0
             17
            0.0
             27
            1.0
             37
            0.0
             76
                 0
            330
            32
              0
            MATERIAL
              5
            12
            102
            {ACAD_XDICTIONARY
            360
            72
            102
            }
            102
            {ACAD_REACTORS
            330
            10
            102
            }
            330
            10
            100
            AcDbMaterial
              1
            ByBlock
              0
            MATERIAL
              5
            11
            102
            {ACAD_XDICTIONARY
            360
            70
            102
            }
            102
            {ACAD_REACTORS
            330
            10
            102
            }
            330
            10
            100
            AcDbMaterial
              1
            ByLayer
              0
            MATERIAL
              5
            13
            102
            {ACAD_XDICTIONARY
            360
            74
            102
            }
            102
            {ACAD_REACTORS
            330
            10
            102
            }
            330
            10
            100
            AcDbMaterial
              1
            Global
              0
            MLINESTYLE
              5
            2C
            102
            {ACAD_REACTORS
            330
            2B
            102
            }
            330
            2B
            100
            AcDbMlineStyle
              2
            STANDARD
             70
                 0
              3
            
             62
               256
             51
            90.0
             52
            90.0
             71
                 2
             49
            0.5
             62
               256
              6
            BYLAYER
             49
            -0.5
             62
               256
              6
            BYLAYER
              0
            ACDBPLACEHOLDER
              5
            F
            102
            {ACAD_REACTORS
            330
            E
            102
            }
            330
            E
              0
            TABLESTYLE
              5
            31
            102
            {ACAD_XDICTIONARY
            360
            82
            102
            }
            102
            {ACAD_REACTORS
            330
            30
            102
            }
            330
            30
            100
            AcDbTableStyle
              3
            Standard
             70
                 0
             71
                 0
             40
            0.06
             41
            0.06
            280
                 0
            281
                 0
              7
            Standard
            140
            0.18
            170
                 2
             62
                 0
             63
                 7
            283
                 0
            274
                -2
            284
                 1
             64
                 0
            275
                -2
            285
                 1
             65
                 0
            276
                -2
            286
                 1
             66
                 0
            277
                -2
            287
                 1
             67
                 0
            278
                -2
            288
                 1
             68
                 0
            279
                -2
            289
                 1
             69
                 0
              7
            Standard
            140
            0.25
            170
                 5
             62
                 0
             63
                 7
            283
                 0
            274
                -2
            284
                 1
             64
                 0
            275
                -2
            285
                 1
             65
                 0
            276
                -2
            286
                 1
             66
                 0
            277
                -2
            287
                 1
             67
                 0
            278
                -2
            288
                 1
             68
                 0
            279
                -2
            289
                 1
             69
                 0
              7
            Standard
            140
            0.18
            170
                 5
             62
                 0
             63
                 7
            283
                 0
            274
                -2
            284
                 1
             64
                 0
            275
                -2
            285
                 1
             65
                 0
            276
                -2
            286
                 1
             66
                 0
            277
                -2
            287
                 1
             67
                 0
            278
                -2
            288
                 1
             68
                 0
            279
                -2
            289
                 1
             69
                 0
              0
            VISUALSTYLE
              5
            1A
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            2dWireframe
             70
                 4
             71
                 0
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    0
             66
               257
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 0
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            1C
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            3D Hidden
             70
                 6
             71
                 1
             72
                 2
             73
                 2
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 2
             91
                    2
             64
                 7
             65
               257
             75
                 2
            175
                 1
             42
            40.0
             92
                    0
             66
               257
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 3
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 0
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            1B
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            3dWireframe
             70
                 5
             71
                 0
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    0
             66
               257
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 0
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            19
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Basic
             70
                 7
             71
                 1
             72
                 0
             73
                 1
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 0
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            20
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Brighten
             70
                12
             71
                 2
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            50.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            24
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            ColorChange
             70
                16
             71
                 2
             72
                 2
             73
                 3
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 8
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 8
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            1D
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Conceptual
             70
                 9
             71
                 3
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 2
             91
                    2
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            40.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 3
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 0
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            1F
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Dim
             70
                11
             71
                 2
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            -50.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            23
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Facepattern
             70
                15
             71
                 2
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            15
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Flat
             70
                 0
             71
                 2
             72
                 1
             73
                 1
             90
                    2
             40
            -0.6
             41
            30.0
             62
                 5
             63
                 7
             74
                 0
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                   13
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            16
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            FlatWithEdges
             70
                 1
             71
                 2
             72
                 1
             73
                 1
             90
                    2
             40
            -0.6
             41
            30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    0
             66
               257
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                   13
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            17
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Gouraud
             70
                 2
             71
                 2
             72
                 2
             73
                 1
             90
                    2
             40
            -0.6
             41
            30.0
             62
                 5
             63
                 7
             74
                 0
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    0
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                   13
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            18
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            GouraudWithEdges
             70
                 3
             71
                 2
             72
                 2
             73
                 1
             90
                    2
             40
            -0.6
             41
            30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    0
             66
               257
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                   13
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            22
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Linepattern
             70
                14
             71
                 2
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 7
            175
                 7
             42
            1.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            1E
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Realistic
             70
                 8
             71
                 2
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    0
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 8
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                   13
             44
            0.0
            173
                 0
            291
                 0
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            21
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Thicken
             70
                13
             71
                 2
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                   12
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            DICTIONARYVAR
              5
            6B
            102
            {ACAD_REACTORS
            330
            6A
            102
            }
            330
            6A
            100
            DictionaryVariables
            280
                 0
              1
            STANDARD
              0
            DICTIONARYVAR
              5
            6E
            102
            {ACAD_REACTORS
            330
            6A
            102
            }
            330
            6A
            100
            DictionaryVariables
            280
                 0
              1
            1
              0
            DICTIONARYVAR
              5
            6D
            102
            {ACAD_REACTORS
            330
            6A
            102
            }
            330
            6A
            100
            DictionaryVariables
            280
                 0
              1
            0
              0
            DICTIONARYVAR
              5
            6C
            102
            {ACAD_REACTORS
            330
            6A
            102
            }
            330
            6A
            100
            DictionaryVariables
            280
                 0
              1
            127
              0
            DICTIONARY
              5
            86
            330
            39
            100
            AcDbDictionary
            280
                 1
            281
                 1
              3
            ACAD_XREC_ROUNDTRIP
            360
            87
              0
            DICTIONARY
              5
            84
            330
            35
            100
            AcDbDictionary
            280
                 1
            281
                 1
              3
            ACAD_XREC_ROUNDTRIP
            360
            85
              0
            DICTIONARY
              5
            72
            330
            12
            100
            AcDbDictionary
            280
                 1
            281
                 1
              3
            ACAD_XREC_ROUNDTRIP
            360
            73
              0
            DICTIONARY
              5
            70
            330
            11
            100
            AcDbDictionary
            280
                 1
            281
                 1
              3
            ACAD_XREC_ROUNDTRIP
            360
            71
              0
            DICTIONARY
              5
            74
            330
            13
            100
            AcDbDictionary
            280
                 1
            281
                 1
              3
            ACAD_XREC_ROUNDTRIP
            360
            75
              0
            DICTIONARY
              5
            82
            330
            31
            100
            AcDbDictionary
            280
                 1
            281
                 1
              3
            ACAD_XREC_ROUNDTRIP
            360
            83
              0
            XRECORD
              5
            87
            102
            {ACAD_REACTORS
            330
            86
            102
            }
            330
            86
            100
            AcDbXrecord
            280
                 1
            102
            SHADEPLOT
             70
                 0
            102
            SHADEPLOTRESLEVEL
             70
                 2
            102
            SHADEPLOTCUSTOMDPI
             70
               300
              0
            XRECORD
              5
            85
            102
            {ACAD_REACTORS
            330
            84
            102
            }
            330
            84
            100
            AcDbXrecord
            280
                 1
            102
            SHADEPLOT
             70
                 0
            102
            SHADEPLOTRESLEVEL
             70
                 2
            102
            SHADEPLOTCUSTOMDPI
             70
               300
              0
            XRECORD
              5
            73
            102
            {ACAD_REACTORS
            330
            72
            102
            }
            330
            72
            100
            AcDbXrecord
            280
                 1
            102
            MATERIAL
            148
            0.0
            149
            0.0
            149
            0.0
             93
                    0
             94
                   63
            282
                 0
             72
                 1
             77
                 1
            171
                 1
            175
                 1
            179
                 1
            273
                 0
              0
            XRECORD
              5
            71
            102
            {ACAD_REACTORS
            330
            70
            102
            }
            330
            70
            100
            AcDbXrecord
            280
                 1
            102
            MATERIAL
            148
            0.0
            149
            0.0
            149
            0.0
             93
                    0
             94
                   63
            282
                 0
             72
                 1
             77
                 1
            171
                 1
            175
                 1
            179
                 1
            273
                 0
              0
            XRECORD
              5
            75
            102
            {ACAD_REACTORS
            330
            74
            102
            }
            330
            74
            100
            AcDbXrecord
            280
                 1
            102
            MATERIAL
            148
            0.0
            149
            0.0
            149
            0.0
             93
                    0
             94
                   63
            282
                 0
             72
                 1
             77
                 1
            171
                 1
            175
                 1
            179
                 1
            273
                 0
              0
            XRECORD
              5
            83
            102
            {ACAD_REACTORS
            330
            82
            102
            }
            330
            82
            100
            AcDbXrecord
            280
                 1
            102
            ACAD_ROUNDTRIP_PRE2007_TABLESTYLE
             90
                  512
             91
                    0
              1
            
             92
                  512
             93
                    0
              2
            
             94
                  512
             95
                    0
              3
            
              0
            ENDSEC
            0
            EOF
        """.trimIndent())
        writer.newLine()
    }
}