package com.jpaver.trianglelist

import android.util.Log
import java.io.BufferedWriter

class DxfFileWriter( trilist: TriangleList ): DrawingFileWriter() {
    override var trilist_ = trilist
    override lateinit var dedlist_: DeductionList// = deductionList

    val numvector_ = trilist_.sokutenListVector
    lateinit var writer_: BufferedWriter
    lateinit var drawingLength_: PointXY // = drawingLength
    val pageNum_ = 0
    var myDXFscale = 1000f //* setScale(drawingLength)    //metric to mill
    val mScale = 11.9f*4f//12.5f

    var isDebug_ = false
    var isReverse_ = false;

    val texScale = trilist_.getPrintTextScale( 1f , "dxf")
    var scale_ = trilist_.getPrintScale(1f)//setScale(drawingLength)
    override var sizeX_ = 42000f * scale_
    override var sizeY_ = 29700f * scale_
    val vpCenterX_ = sizeX_ * 0.5f
    val vpCenterY_ = sizeY_ * 0.5f

    var entityHandle = 100

    override fun save(){
        if(writer_ == null) return

        writeHeader()
        /* writeDXFTables(writer)
         writeDXFBlock(writer)
         */
        writeEntities()
        writeFooter()

        Log.d("DxfFileWriter", "Writer Process Done.")

    }

    fun alignVByVector(num: Int, p1: PointXY, p2: PointXY ): Int{
        // 垂直方向の文字位置合わせタイプ(省略可能、既定 = 0): 整数コード(ビットコードではありません):
        // 0 = 基準線、1 = 下、2 = 中央、3 = 上
        // ベクトルの方向でB,Cを表現するなら
        // x軸の方向で正負を表す。正の時は下1が内、負の時は上3が内。

        // inner:3, outer:1 in Tri
        // ただし、Triangleで外(1)を指定しているときは、そちらを優先したい。
        // 正の時は上３が外、負の時は下１が外。
        val isVectorRight = p1.vectorTo(p2).side()
        if( num == 1 ){
            if(  isVectorRight >= 0 ) return 1
            if(  isVectorRight <  0 ) return 3
        }

        // 基本は内側。正の時は下1が内、負の時は上3が内。
        if(  isVectorRight >= 0 ) return 3
        if(  isVectorRight <  0 ) return 1


        return num
    }

    override fun writeTriangle(tri: Triangle){
        // arrange
        val pca = tri.pointCA_
        val pab = tri.pointAB_
        val pbc = tri.pointBC_

        val textsize: Float = texScale
        val textsize2: Float = texScale

        //if( tri.myAngle_ > 90 ) dimA = 1
        //if( tri.myAngle_ > 270 ) dimA = 3
        var dimA = alignVByVector(tri.myDimAlignA_, pca, pab)
        val dimB = alignVByVector(tri.myDimAlignB_, pab, pbc)//flip(tri.myDimAlignB_, tri.dimAngleB_ )
        val dimC = alignVByVector(tri.myDimAlignC_, pbc, pca)//flip(tri.myDimAlignC_, tri.dimAngleC_ )

        var la = tri.lengthAforce_.formattedString(2)
        var lb = tri.lengthBforce_.formattedString(2)
        var lc = tri.lengthCforce_.formattedString(2)


        if( isDebug_ == true ){
            la += "-"+ dimA
            lb += "-"+ dimB
            lc += "-"+ dimC
        }

        // TriLines
        writeLine( pca, pab, 7)
        writeLine( pab, pbc, 7)
        writeLine( pbc, pca, 7)

        // DimTexts
        if(tri.getMyNumber_()==1 || tri.parentBC > 2)
            writeTextDimension(dimA, la, tri.dimPointA_, pab.calcDimAngle(pca))
        writeTextDimension(dimB, lb, tri.dimPointB_, pbc.calcDimAngle(pab))
        writeTextDimension(dimC, lc, tri.dimPointC_, pca.calcDimAngle(pbc))

        // 番号
        val pn = tri.pointNumberAutoAligned_
        val pc = tri.pointCenter_
        val circleSize = textsize *0.8f
        // 本体
        writeCircle(pn, textsize, 5)
        writeTextNumber(tri)

        //引き出し矢印線の描画
        if( tri.isCollide(tri.pointNumber_) == false ){
            val pcOffsetToN = pc.offset(pn, circleSize * 0.5f )
            val pnOffsetToC = pn.offset(pc, circleSize * 1.2f )
            val arrowTail = pcOffsetToN.offset(pn, pcOffsetToN.lengthTo(pnOffsetToC) * 0.7f).rotate(pcOffsetToN, 5f)

            writeLine( pcOffsetToN, pnOffsetToC, 5)
            writeLine( pcOffsetToN, arrowTail, 5)
        }


        // 測点
        if(tri.getMyName_() != "") {
            writeText( tri.getMyName_(), pab.offset(pca, -1.25f), 5, textsize2, 1, 1, pab.calcSokAngle( pca, numvector_ ) )
            writeLine( pab.offset(pca, -tri.getMyName_().length*0.5f), pab.offset(pca, -0.25f), 5)
        }
    }

    fun writeTextDimension(verticalalign: Int, len: String, p1: PointXY, angle: Float){
        writeText( len, p1, 7, texScale, 1, verticalalign, angle)
    }

    fun writeTextNumber(tri: Triangle){
        writeText( tri.getMyNumber_().toString(), tri.pointNumberAutoAligned_, 5, texScale, 1, 2,0f)
    }

    override fun writeText( text: String, point: PointXY, color: Int, textsize: Float, alignH: Int, alignV:Int, angle: Float ){
        var x = point.x *myDXFscale //- ( alignV * 30 - 60 )// a offset when V is 3 to 1. V is 1 to -1.
        var y = point.y *myDXFscale //- ( alignV * 30 - 60 )
        val ts = textsize * myDXFscale

        // its not effective..?
        if( alignV == 3) {
            if( angle < 0 ){
                x -= 50f
                y -= 50f
            }
        }

        entityHandle += 1

        writer_.write("""
            0
            TEXT
            5
            $entityHandle
            330
            36
            100
            AcDbEntity
            8
            0
            62
            ${color}
            100
            AcDbText
            10
            $x
            20
            $y
            30
            0.0
            40
            ${ts.formattedString(0)}
            1
            ${text}
            41
            1.00
            7
            DimStandard
            72
            ${alignH}
            11
            $x
            21
            $y
            31
            0.0
            50
            $angle
            51
            0.0
            100
            AcDbText
            73
            ${alignV}
        """.trimIndent())
        writer_.newLine()
    }

    override fun writeLine(p1: PointXY, p2: PointXY, color: Int) {
        val ax = p1.x *myDXFscale
        val ay = p1.y *myDXFscale
        val bx = p2.x *myDXFscale
        val by = p2.y *myDXFscale

        entityHandle += 1

        writer_.write(
                """
                0
                LINE
                5
                $entityHandle
                330
                36
                100
                AcDbEntity
                8
                0
                100
                AcDbLine
                10
                $ax
                20
                $ay
                30
                0.0
                11
                $bx
                21
                $by
                31
                0.0
                62
                $color
            """.trimIndent()
        )
        writer_.newLine()
    }

    override fun writeCircle(point: PointXY, size: Float, color: Int){
        val x = point.x *myDXFscale
        val y = point.y *myDXFscale
        val s = size * myDXFscale

        entityHandle += 1

        writer_.write("""
            0
            CIRCLE
            5
            $entityHandle
            330
            36
            100
            AcDbEntity
            8
            0
            62
            $color
            100
            AcDbCircle
            10
            $x
            20
            $y
            30
            0.0
            40
            ${s} 
        """.trimIndent())
        writer_.newLine()
    }

    override fun writeTextAndLine( st: String, p1: PointXY, p2: PointXY, textsize: Float){
        writeText( st, p1.plus(0.2f,0.1f), 1, textsize, 0)
        writeLine( p1, p2, 1)
    }

    fun writeOuterFrameAndTitle(){
        // 外枠描画
        writeRect( PointXY(21f,14.85f),40f,27f, 7)

        // 上のタイトル
        writeText( rStr_.tTitle_, PointXY(21f, 27.1f), 7, 0.35f, 1)
        writeText( rosenname_, PointXY(21f,26f), 7, 0.3f, 1 )

        writeLine( PointXY(19f,27f), PointXY(23f,27f),7)
        writeLine( PointXY(19f,26.9f), PointXY(23f,26.9f),7)
    }

    fun writeFrame(wrtr: BufferedWriter){
        myDXFscale = 1000f  * scale_//setScale(drawingLength_)  // 1:scale

        writeOuterFrameAndTitle()

        //右下のタイトル枠
        writeLine( PointXY(31f,7.35f), PointXY(41f,7.35f),7) //yoko
        writeLine( PointXY(31f,1.35f), PointXY(31f,7.35f),7) //tate
        writeLine( PointXY(33f,1.35f), PointXY(33f,7.35f),7) //uchi-tate

        writeLine( PointXY(31f,6.35f), PointXY(41f,6.35f),7)
        writeLine( PointXY(31f,5.35f), PointXY(41f,5.35f),7)
        writeLine( PointXY(31f,4.35f), PointXY(41f,4.35f),7)
        writeLine( PointXY(31f,3.35f), PointXY(41f,3.35f),7)
        writeLine( PointXY(31f,2.35f), PointXY(41f,2.35f),7)
        writeLine( PointXY(36f,2.35f), PointXY(36f,3.35f),7)
        writeLine( PointXY(38f,2.35f), PointXY(38f,3.35f),7)

        val tss = 0.2f

        val st = scale_*100f
        val strx = 33.5f

        val xr = strx
        val yb = 6.7f
        val yo = 0.2f
        val uw = 160f
        val tt = 0
        val ofs = 3f

        // 題字
        writeText( rStr_.tCname_, PointXY(32f, 6.7f), 7, tss, 1)
        writeText( rStr_.tDtype_, PointXY(32f, 5.7f), 7, tss, 1)
        writeText( rStr_.tDname_, PointXY(32f, 4.7f), 7, tss, 1)
        writeText( rStr_.tDateHeader_, PointXY(32f, 3.7f), 7, tss, 1)
        writeText( rStr_.tScale_, PointXY(32f, 2.7f), 7, tss, 1)
        writeText( rStr_.tNum_, PointXY(37f, 2.7f), 7, tss, 1)
        writeText( rStr_.tAname_, PointXY(32f, 1.7f), 7, tss, 1)
        writeText( rStr_.tCredit_, PointXY(7f, 1f), 7, tss, 1 )

        // 内容
        // 工事名
        if( koujiname_.length > 20 ) {
            if( koujiname_.contains(" ") ){
                val array = koujiname_.split(' ')
                writeText( array[0], PointXY(xr - tt, yb + yo ), 7, tss, 0)
                writeText( array[1], PointXY(xr - tt, yb - yo ), 7, tss, 0)
            }
            else{
                val array1 = koujiname_.substring(0, 20)
                val array2 = koujiname_.substring(20, koujiname_.length)
                writeText( array1, PointXY(xr - tt, yb + yo ), 7, tss, 0)
                writeText( array2, PointXY(xr - tt, yb - yo ), 7, tss, 0)
            }
        }
        else {
            writeText( koujiname_, PointXY(xr-tt, yb ), 7, tss, 0)
        }
        writeText( rStr_.tTitle_, PointXY(strx, 5.7f), 7, tss, 0)
        writeText( rosenname_, PointXY(strx, 4.7f), 7, tss, 0)
        writeText( rStr_.tDate_, PointXY(strx, 3.7f), 7, tss, 0)
        writeText( "1/${st.toInt()} (A3)", PointXY(34.5f, 2.7f), 7, tss, 1)
        writeText( zumennum_, PointXY(39.5f, 2.7f), 7, tss, 1)
        writeText( gyousyaname_, PointXY(strx, 1.7f), 7, tss, 0)

        myDXFscale = 1000f  // 1:1
    }

    override fun writeDeduction( ded: Deduction ){

        //val ded = dedlist_.get( dednumber )
        val textsize: Float = 0.35f
        val infoStrLength = ded.info_.length*textsize+0.3f
        val point = ded.point
        val pointFlag = ded.pointFlag
        var textOffsetX = 0f
        if( ded.type == "Box" ) textOffsetX = -0.5f

        if(point.x <= pointFlag.x) {  //ptFlag is RIGHT from pt
            writeLine( point, pointFlag, 1)
            writeTextAndLine( ded.info_, pointFlag, pointFlag.plus(infoStrLength + textOffsetX,0f), textsize)
        } else {                     //ptFlag is LEFT from pt
            writeLine( point, pointFlag, 1)
            writeTextAndLine( ded.info_, pointFlag.plus(-ded.getInfo().length*textsize - textOffsetX,0f), pointFlag, textsize)
        }

        if(ded.type == "Circle") writeCircle(point, ded.lengthX/2, 1)
        if(ded.type == "Box")    writeDedRect(ded, 1)//writeDXFRect(wrtr, point, ded.lengthX, ded.lengthY, 1)
    }

    fun writeDedRect(ded: Deduction, color: Int){
        ded.shapeAngle_ = -ded.shapeAngle_ // 逆回転
        ded.setBox( 1f )
        writeLine( ded.plt, ded.plb, color)
        writeLine( ded.plt, ded.prt, color)
        writeLine( ded.prt, ded.prb, color)
        writeLine( ded.plb, ded.prb, color)
    }

    override fun writeEntities(){

        var myDXFTriList = trilist_.clone()
        var myDXFDedList = dedlist_.clone()

//        myDXFDedList.rotate(PointXY(0f,0f), myDXFTriList.rotateByLength("laydown"))
        // Ｙ軸方向反転、かつビュースケールで割り戻して大きさをtrilistと揃える。
        myDXFDedList.scale(PointXY(0f,0f),1/mScale,-1/mScale)

        val center = PointXY(21f*scale_, 14.85f*scale_)
        val tricenter = myDXFTriList.center
        myDXFDedList.move(PointXY(center.x-tricenter.x,center.y-tricenter.y))
        myDXFTriList.move(PointXY(center.x-tricenter.x,center.y-tricenter.y))
        //myDXFTriList.move(PointXY(21f,14.85f))
//        myDXFDedList.move(PointXY(21f,14.85f))

        writer_.write("""
            0
            SECTION
            2
            ENTITIES
        """.trimIndent())
        writer_.newLine()


        val trilistNumbered = myDXFTriList.numbered( startTriNumber_ )
        if( isReverse_ == true ) {
            trilistNumbered.reverse()
            myDXFDedList.reverse()
        };

        for (index in 1 .. myDXFTriList.size()) {
            writeTriangle(trilistNumbered.get(index))
        }

        // アウトラインの描画
        myDXFTriList.setChildsToAllParents()
        val outlineLists = myDXFTriList.outlineLists //ArrayList<PointXY>()
        val array = ArrayList<PointXY>()
        myDXFTriList.traceOrJumpForward(0, 0, array )
        //if( array.size > 0 ) writeDXFTriOutlines( wrtr, array )
//
        if( outlineLists.size > 0 ) for( index in 0 .. outlineLists.size -1 ) writeDXFTriOutlines( writer_, outlineLists.get( index ) )

        // deduction
        for (number in 1 .. myDXFDedList.size()) {
            writeDeduction( myDXFDedList.get(number) )
        }
        writeFrame(writer_)
        writer_.write("""
            0
            ENDSEC
        """.trimIndent())
        writer_.newLine()

        // calcSheet
        writeCalcSheet( )

    }

    fun writeCalcSheet( ){
        var area = 0.0f
        val baseX = sizeX_ + 10f
        var baseY = sizeY_

        for( index in 1 .. trilist_.size() ){
            area += writeCalcSheetLine( trilist_.get(index), baseX, baseY )
            baseY += 50f
        }

    }

    fun writeCalcSheetLine( editObject: EditObject, baseX: Float, baseY: Float ) :Float {
        val param = editObject.getParams()

        writeText( param.n.toString(), PointXY(baseX, baseY), 1, texScale, 1)

        return editObject.getArea()
    }

    fun writeDXFTriOutlines( wrtr: BufferedWriter, array: ArrayList<PointXY> ) {

        entityHandle += 1

        wrtr.write("""
            0
            LWPOLYLINE
            5
            $entityHandle
            100
            AcDbEntity
            8
            0
            100
            AcDbPolyline
            90
            6
            70
            1
            43
            0.0
        """.trimIndent())
        wrtr.newLine()

        for( index in 0 .. array.size - 1 ){
            wrtr.write("""
                10
                ${( array.get( index ).x*myDXFscale )}
                20
                ${( array.get( index ).y*myDXFscale )}                
            """.trimIndent())
            wrtr.newLine()
        }

    }

    fun writeDXFBlock(wrtr: BufferedWriter){
        wrtr.write("""
            0
            SECTION
            2
            BLOCKS
            0
            ENDSEC
        """.trimIndent())
        wrtr.newLine()

    }

    fun writeDXFTables(wrtr: BufferedWriter){
        wrtr.write("""
              0
            SECTION
              2
            TABLES
              0
            TABLE
              2
            VPORT
              5
            8
            330
            0
            100
            AcDbSymbolTable
             70
                 1
              0
            VPORT
              5
            3A
            330
            8
            100
            AcDbSymbolTableRecord
            100
            AcDbViewportTableRecord
              2
            *ACTIVE
             70
                 0
             10
            0.0
             20
            0.0
             11
            1.0
             21
            1.0
             12
            $vpCenterX_
             22
            ${(vpCenterY_*0.1f)}
             13
            0.0
             23
            0.0
             14
            1.0
             24
            1.0
             15
            0.0
             25
            0.0
             16
            0.0
             26
            0.0
             36
            1.0
             17
            0.0
             27
            0.0
             37
            0.0
             40
            ${(sizeX_*0.006f)}
             41
            ${(sizeY_*0.006f)}
             42
            50.0
             43
            0.0
             44
            0.0
             50
            0.0
             51
            0.0
             71
                 0
             72
               100
             73
                 1
             74
                 1
             75
                 0
             76
                 0
             77
                 0
             78
                 0
            281
                 0
             65
                 1
            110
            0.0
            120
            0.0
            130
            0.0
            111
            1.0
            121
            0.0
            131
            0.0
            112
            0.0
            122
            1.0
            132
            0.0
             79
                 0
            146
            0.0
              0
            ENDTAB
              0
            TABLE
              2
            LTYPE
              5
            5
            330
            0
            100
            AcDbSymbolTable
             70
                 1
              0
            LTYPE
              5
            28
            330
            5
            100
            AcDbSymbolTableRecord
            100
            AcDbLinetypeTableRecord
              2
            ByBlock
             70
                 0
              3
            
             72
                65
             73
                 0
             40
            0.0
              0
            LTYPE
              5
            29
            330
            5
            100
            AcDbSymbolTableRecord
            100
            AcDbLinetypeTableRecord
              2
            ByLayer
             70
                 0
              3
            
             72
                65
             73
                 0
             40
            0.0
              0
            LTYPE
              5
            2A
            330
            5
            100
            AcDbSymbolTableRecord
            100
            AcDbLinetypeTableRecord
              2
            Continuous
             70
                 0
              3
            Solid line
             72
                65
             73
                 0
             40
            0.0
              0
            ENDTAB
              0
            TABLE
              2
            LAYER
              5
            2
            330
            0
            100
            AcDbSymbolTable
             70
                 1
              0
            LAYER
              5
            25
            330
            2
            100
            AcDbSymbolTableRecord
            100
            AcDbLayerTableRecord
              2
            0
             70
                 0
             62
                 7
              6
            Continuous
            370
                -3
            390
            F
              0
            ENDTAB
              0
            TABLE
              2
            STYLE
              5
            3
            330
            0
            100
            AcDbSymbolTable
             70
                 2
              0
            STYLE
              5
            26
            330
            3
            100
            AcDbSymbolTableRecord
            100
            AcDbTextStyleTableRecord
              2
            Standard
             70
                 0
             40
            0.0
             41
            1.0
             50
            0.0
             71
                 0
             42
            0.2
              3
            
              4
            
            1001
            ACAD
            1000
            @MS Gothic
            1071
                32817
              0
            STYLE
              5
            3B
            330
            3
            100
            AcDbSymbolTableRecord
            100
            AcDbTextStyleTableRecord
              2
            DIMSTANDARD
             70
                 0
             40
            0.0
             41
            1.0
             50
            0.0
             71
                 0
             42
            0.2
              3
            
              4
            
            1001
            ACAD
            1000
            MS Gothic
            1071
                32817
              0
            ENDTAB
              0
            TABLE
              2
            VIEW
              5
            6
            330
            0
            100
            AcDbSymbolTable
             70
                 0
              0
            ENDTAB
              0
            TABLE
              2
            UCS
              5
            7
            330
            0
            100
            AcDbSymbolTable
             70
                 0
              0
            ENDTAB
              0
            TABLE
              2
            APPID
              5
            9
            330
            0
            100
            AcDbSymbolTable
             70
                 1
              0
            APPID
              5
            27
            330
            9
            100
            AcDbSymbolTableRecord
            100
            AcDbRegAppTableRecord
              2
            ACAD
             70
                 0
              0
            ENDTAB
              0
            TABLE
              2
            DIMSTYLE
              5
            A
            330
            0
            100
            AcDbSymbolTable
             70
                 1
            100
            AcDbDimStyleTable
             71
                 0
              0
            DIMSTYLE
            105
            67
            330
            A
            100
            AcDbSymbolTableRecord
            100
            AcDbDimStyleTableRecord
              2
            Standard
             70
                 0
            340
            26
              0
            ENDTAB
              0
            TABLE
              2
            BLOCK_RECORD
              5
            1
            330
            0
            100
            AcDbSymbolTable
             70
                 0
              0
            BLOCK_RECORD
              5
            36
            330
            1
            100
            AcDbSymbolTableRecord
            100
            AcDbBlockTableRecord
              2
            *Model_Space
            340
            39
              0
            BLOCK_RECORD
              5
            32
            330
            1
            100
            AcDbSymbolTableRecord
            100
            AcDbBlockTableRecord
              2
            *Paper_Space
            340
            35
              0
            ENDTAB
              0
            ENDSEC
              0
            SECTION
              2
            BLOCKS
              0
            BLOCK
              5
            37
            330
            36
            100
            AcDbEntity
              8
            0
            100
            AcDbBlockBegin
              2
            *Model_Space
             70
                 0
             10
            0.0
             20
            0.0
             30
            0.0
              3
            *Model_Space
              1
            
              0
            ENDBLK
              5
            38
            330
            36
            100
            AcDbEntity
              8
            0
            100
            AcDbBlockEnd
              0
            BLOCK
              5
            33
            330
            32
            100
            AcDbEntity
             67
                 1
              8
            0
            100
            AcDbBlockBegin
              2
            *Paper_Space
             70
                 0
             10
            0.0
             20
            0.0
             30
            0.0
              3
            *Paper_Space
              1
            
              0
            ENDBLK
              5
            34
            330
            32
            100
            AcDbEntity
             67
                 1
              8
            0
            100
            AcDbBlockEnd
              0
            ENDSEC
        """.trimIndent())
        wrtr.newLine()

    }

    override fun writeHeader(){
        val scaleX = 42000*scale_
        val scaleY = 29700*scale_

        writer_.write("""
             0
            SECTION
              2
            HEADER
              9
            ${'$'}ACADVER
              1
            AC1015
              9
            ${'$'}ACADMAINTVER
             70
                20
              9
            ${'$'}DWGCODEPAGE
              3
            ANSI_932
              9
            ${'$'}INSBASE
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}EXTMIN
            10
            0.0
            20
            0.0
            30
            0.0
            9
            ${'$'}EXTMAX
            10
            ${scaleX}
            20
            ${scaleY}
            30
            0.0
            9
            ${'$'}LIMMIN
            10
            0.0
            20
            0.0
            9
            ${'$'}LIMMAX
            10
            ${scaleX*1.2}
            20
            ${scaleY*1.2}
            9
            ${'$'}ORTHOMODE
             70
                 0
              9
            ${'$'}REGENMODE
             70
                 1
              9
            ${'$'}FILLMODE
             70
                 1
              9
            ${'$'}QTEXTMODE
             70
                 0
              9
            ${'$'}MIRRTEXT
             70
                 0
              9
            ${'$'}LTSCALE
             40
            1.0
              9
            ${'$'}ATTMODE
             70
                 1
              9
            ${'$'}TEXTSIZE
             40
            0.2
              9
            ${'$'}TRACEWID
             40
            0.05
              9
            ${'$'}TEXTSTYLE
              7
            DIMSTANDARD
              9
            ${'$'}CLAYER
              8
            0
              9
            ${'$'}CELTYPE
              6
            Continuous
              9
            ${'$'}CECOLOR
             62
               256
              9
            ${'$'}CELTSCALE
             40
            1.0
              9
            ${'$'}DISPSILH
             70
                 0
              9
            ${'$'}DIMSCALE
             40
            1.0
              9
            ${'$'}DIMASZ
             40
            0.18
              9
            ${'$'}DIMEXO
             40
            0.0625
              9
            ${'$'}DIMDLI
             40
            0.38
              9
            ${'$'}DIMRND
             40
            0.0
              9
            ${'$'}DIMDLE
             40
            0.0
              9
            ${'$'}DIMEXE
             40
            0.18
              9
            ${'$'}DIMTP
             40
            0.0
              9
            ${'$'}DIMTM
             40
            0.0
              9
            ${'$'}DIMTXT
             40
            0.18
              9
            ${'$'}DIMCEN
             40
            0.09
              9
            ${'$'}DIMTSZ
             40
            0.0
              9
            ${'$'}DIMTOL
             70
                 0
              9
            ${'$'}DIMLIM
             70
                 0
              9
            ${'$'}DIMTIH
             70
                 1
              9
            ${'$'}DIMTOH
             70
                 1
              9
            ${'$'}DIMSE1
             70
                 0
              9
            ${'$'}DIMSE2
             70
                 0
              9
            ${'$'}DIMTAD
             70
                 0
              9
            ${'$'}DIMZIN
             70
                 0
              9
            ${'$'}DIMBLK
              1
            
              9
            ${'$'}DIMASO
             70
                 1
              9
            ${'$'}DIMSHO
             70
                 1
              9
            ${'$'}DIMPOST
              1
            
              9
            ${'$'}DIMAPOST
              1
            
              9
            ${'$'}DIMALT
             70
                 0
              9
            ${'$'}DIMALTD
             70
                 2
              9
            ${'$'}DIMALTF
             40
            25.4
              9
            ${'$'}DIMLFAC
             40
            1.0
              9
            ${'$'}DIMTOFL
             70
                 0
              9
            ${'$'}DIMTVP
             40
            0.0
              9
            ${'$'}DIMTIX
             70
                 0
              9
            ${'$'}DIMSOXD
             70
                 0
              9
            ${'$'}DIMSAH
             70
                 0
              9
            ${'$'}DIMBLK1
              1
            
              9
            ${'$'}DIMBLK2
              1
            
              9
            ${'$'}DIMSTYLE
              2
            Standard
              9
            ${'$'}DIMCLRD
             70
                 0
              9
            ${'$'}DIMCLRE
             70
                 0
              9
            ${'$'}DIMCLRT
             70
                 0
              9
            ${'$'}DIMTFAC
             40
            1.0
              9
            ${'$'}DIMGAP
             40
            0.09
              9
            ${'$'}DIMJUST
             70
                 0
              9
            ${'$'}DIMSD1
             70
                 0
              9
            ${'$'}DIMSD2
             70
                 0
              9
            ${'$'}DIMTOLJ
             70
                 1
              9
            ${'$'}DIMTZIN
             70
                 0
              9
            ${'$'}DIMALTZ
             70
                 0
              9
            ${'$'}DIMALTTZ
             70
                 0
              9
            ${'$'}DIMUPT
             70
                 0
              9
            ${'$'}DIMDEC
             70
                 4
              9
            ${'$'}DIMTDEC
             70
                 4
              9
            ${'$'}DIMALTU
             70
                 2
              9
            ${'$'}DIMALTTD
             70
                 2
              9
            ${'$'}DIMTXSTY
              7
            Standard
              9
            ${'$'}DIMAUNIT
             70
                 0
              9
            ${'$'}DIMADEC
             70
                 0
              9
            ${'$'}DIMALTRND
             40
            0.0
              9
            ${'$'}DIMAZIN
             70
                 0
              9
            ${'$'}DIMDSEP
             70
                46
              9
            ${'$'}DIMATFIT
             70
                 3
              9
            ${'$'}DIMFRAC
             70
                 0
              9
            ${'$'}DIMLDRBLK
              1
            
              9
            ${'$'}DIMLUNIT
             70
                 2
              9
            ${'$'}DIMLWD
             70
                -2
              9
            ${'$'}DIMLWE
             70
                -2
              9
            ${'$'}DIMTMOVE
             70
                 0
              9
            ${'$'}LUNITS
             70
                 2
              9
            ${'$'}LUPREC
             70
                 4
              9
            ${'$'}SKETCHINC
             40
            0.1
              9
            ${'$'}FILLETRAD
             40
            0.0
              9
            ${'$'}AUNITS
             70
                 0
              9
            ${'$'}AUPREC
             70
                 0
              9
            ${'$'}MENU
              1
            .
              9
            ${'$'}ELEVATION
             40
            0.0
              9
            ${'$'}PELEVATION
             40
            0.0
              9
            ${'$'}THICKNESS
             40
            0.0
              9
            ${'$'}LIMCHECK
             70
                 0
              9
            ${'$'}CHAMFERA
             40
            0.0
              9
            ${'$'}CHAMFERB
             40
            0.0
              9
            ${'$'}CHAMFERC
             40
            0.0
              9
            ${'$'}CHAMFERD
             40
            0.0
              9
            ${'$'}SKPOLY
             70
                 0
              9
            ${'$'}TDCREATE
             40
            2459198.769561898
              9
            ${'$'}TDUCREATE
             40
            2459198.394561898
              9
            ${'$'}TDUPDATE
             40
            2459198.771185336
              9
            ${'$'}TDUUPDATE
             40
            2459198.396185336
              9
            ${'$'}TDINDWG
             40
            0.0014492593
              9
            ${'$'}TDUSRTIMER
             40
            0.0014490856
              9
            ${'$'}USRTIMER
             70
                 1
              9
            ${'$'}ANGBASE
             50
            0.0
              9
            ${'$'}ANGDIR
             70
                 0
              9
            ${'$'}PDMODE
             70
                 0
              9
            ${'$'}PDSIZE
             40
            0.0
              9
            ${'$'}PLINEWID
             40
            0.0
              9
            ${'$'}SPLFRAME
             70
                 0
              9
            ${'$'}SPLINETYPE
             70
                 6
              9
            ${'$'}SPLINESEGS
             70
                 8
              9
            ${'$'}HANDSEED
              5
            88
              9
            ${'$'}SURFTAB1
             70
                 6
              9
            ${'$'}SURFTAB2
             70
                 6
              9
            ${'$'}SURFTYPE
             70
                 6
              9
            ${'$'}SURFU
             70
                 6
              9
            ${'$'}SURFV
             70
                 6
              9
            ${'$'}UCSBASE
              2
            
              9
            ${'$'}UCSNAME
              2
            
              9
            ${'$'}UCSORG
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSXDIR
             10
            1.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSYDIR
             10
            0.0
             20
            1.0
             30
            0.0
              9
            ${'$'}UCSORTHOREF
              2
            
              9
            ${'$'}UCSORTHOVIEW
             70
                 0
              9
            ${'$'}UCSORGTOP
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSORGBOTTOM
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSORGLEFT
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSORGRIGHT
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSORGFRONT
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}UCSORGBACK
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSBASE
              2
            
              9
            ${'$'}PUCSNAME
              2
            
              9
            ${'$'}PUCSORG
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSXDIR
             10
            1.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSYDIR
             10
            0.0
             20
            1.0
             30
            0.0
              9
            ${'$'}PUCSORTHOREF
              2
            
              9
            ${'$'}PUCSORTHOVIEW
             70
                 0
              9
            ${'$'}PUCSORGTOP
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSORGBOTTOM
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSORGLEFT
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSORGRIGHT
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSORGFRONT
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PUCSORGBACK
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}USERI1
             70
                 0
              9
            ${'$'}USERI2
             70
                 0
              9
            ${'$'}USERI3
             70
                 0
              9
            ${'$'}USERI4
             70
                 0
              9
            ${'$'}USERI5
             70
                 0
              9
            ${'$'}USERR1
             40
            0.0
              9
            ${'$'}USERR2
             40
            0.0
              9
            ${'$'}USERR3
             40
            0.0
              9
            ${'$'}USERR4
             40
            0.0
              9
            ${'$'}USERR5
             40
            0.0
              9
            ${'$'}WORLDVIEW
             70
                 1
              9
            ${'$'}SHADEDGE
             70
                 3
              9
            ${'$'}SHADEDIF
             70
                70
              9
            ${'$'}TILEMODE
             70
                 1
              9
            ${'$'}MAXACTVP
             70
                64
              9
            ${'$'}PINSBASE
             10
            0.0
             20
            0.0
             30
            0.0
              9
            ${'$'}PLIMCHECK
             70
                 0
              9
            ${'$'}PEXTMIN
             10
            1.000000000000000E+20
             20
            1.000000000000000E+20
             30
            1.000000000000000E+20
              9
            ${'$'}PEXTMAX
             10
            -1.000000000000000E+20
             20
            -1.000000000000000E+20
             30
            -1.000000000000000E+20
              9
            ${'$'}PLIMMIN
             10
            0.0
             20
            0.0
              9
            ${'$'}PLIMMAX
             10
            12.0
             20
            9.0
              9
            ${'$'}UNITMODE
             70
                 0
              9
            ${'$'}VISRETAIN
             70
                 1
              9
            ${'$'}PLINEGEN
             70
                 0
              9
            ${'$'}PSLTSCALE
             70
                 1
              9
            ${'$'}TREEDEPTH
             70
              3020
              9
            ${'$'}CMLSTYLE
              2
            Standard
              9
            ${'$'}CMLJUST
             70
                 0
              9
            ${'$'}CMLSCALE
             40
            1.0
              9
            ${'$'}PROXYGRAPHICS
             70
                 1
              9
            ${'$'}MEASUREMENT
             70
                 0
              9
            ${'$'}CELWEIGHT
            370
                -1
              9
            ${'$'}ENDCAPS
            280
                 0
              9
            ${'$'}JOINSTYLE
            280
                 0
              9
            ${'$'}LWDISPLAY
            290
                 0
              9
            ${'$'}INSUNITS
             70
                 0
              9
            ${'$'}HYPERLINKBASE
              1
            
              9
            ${'$'}STYLESHEET
              1
            
              9
            ${'$'}XEDIT
            290
                 1
              9
            ${'$'}CEPSNTYPE
            380
                 0
              9
            ${'$'}PSTYLEMODE
            290
                 1
              9
            ${'$'}FINGERPRINTGUID
              2
            {68315CFD-F49C-40F0-8814-45FE33FC9483}
              9
            ${'$'}VERSIONGUID
              2
            {D8A8B553-77FB-4109-8835-302D291E56A1}
              9
            ${'$'}EXTNAMES
            290
                 1
              9
            ${'$'}PSVPSCALE
             40
            0.0
              9
            ${'$'}OLESTARTUP
            290
                 0
            0
            ENDSEC
            0
            SECTION
              2
            CLASSES
              0
            CLASS
              1
            ACDBDICTIONARYWDFLT
              2
            AcDbDictionaryWithDefault
              3
            ObjectDBX Classes
             90
                    0
            280
                 0
            281
                 0
              0
            CLASS
              1
            MATERIAL
              2
            AcDbMaterial
              3
            ObjectDBX Classes
             90
                 1024
            280
                 0
            281
                 0
              0
            CLASS
              1
            VISUALSTYLE
              2
            AcDbVisualStyle
              3
            ObjectDBX Classes
             90
                 4095
            280
                 0
            281
                 0
              0
            CLASS
              1
            TABLESTYLE
              2
            AcDbTableStyle
              3
            ObjectDBX Classes
             90
                 4095
            280
                 0
            281
                 0
              0
            CLASS
              1
            DICTIONARYVAR
              2
            AcDbDictionaryVar
              3
            ObjectDBX Classes
             90
                    0
            280
                 0
            281
                 0
              0
            CLASS
              1
            ACDBPLACEHOLDER
              2
            AcDbPlaceHolder
              3
            ObjectDBX Classes
             90
                    0
            280
                 0
            281
                 0
              0
            CLASS
              1
            LAYOUT
              2
            AcDbLayout
              3
            ObjectDBX Classes
             90
                    0
            280
                 0
            281
                 0
              0
            ENDSEC
        """.trimIndent())
        writer_.newLine()

        writeDXFTables(writer_)

    }

    override fun writeFooter(){
        writer_.write("""
              0
            SECTION
              2
            OBJECTS
              0
            DICTIONARY
              5
            C
            330
            0
            100
            AcDbDictionary
            281
                 1
              3
            ACAD_COLOR
            350
            2F
              3
            ACAD_GROUP
            350
            D
              3
            ACAD_LAYOUT
            350
            2E
              3
            ACAD_MATERIAL
            350
            10
              3
            ACAD_MLINESTYLE
            350
            2B
              3
            ACAD_PLOTSETTINGS
            350
            2D
              3
            ACAD_PLOTSTYLENAME
            350
            E
              3
            ACAD_TABLESTYLE
            350
            30
              3
            ACAD_VISUALSTYLE
            350
            14
              3
            AcDbVariableDictionary
            350
            6A
              3
            DWGPROPS
            350
            81
              0
            DICTIONARY
              5
            2F
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              0
            DICTIONARY
              5
            D
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              0
            DICTIONARY
              5
            2E
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            Model
            350
            39
              3
            レイアウト1
            350
            35
              0
            DICTIONARY
              5
            10
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            ByBlock
            350
            12
              3
            ByLayer
            350
            11
              3
            Global
            350
            13
              0
            DICTIONARY
              5
            2B
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            Standard
            350
            2C
              0
            DICTIONARY
              5
            2D
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              0
            ACDBDICTIONARYWDFLT
              5
            E
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            Normal
            350
            F
            100
            AcDbDictionaryWithDefault
            340
            F
              0
            DICTIONARY
              5
            30
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            Standard
            350
            31
              0
            DICTIONARY
              5
            14
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            2dWireframe
            350
            1A
              3
            3D Hidden
            350
            1C
              3
            3dWireframe
            350
            1B
              3
            Basic
            350
            19
              3
            Brighten
            350
            20
              3
            ColorChange
            350
            24
              3
            Conceptual
            350
            1D
              3
            Dim
            350
            1F
              3
            Facepattern
            350
            23
              3
            Flat
            350
            15
              3
            FlatWithEdges
            350
            16
              3
            Gouraud
            350
            17
              3
            GouraudWithEdges
            350
            18
              3
            Linepattern
            350
            22
              3
            Realistic
            350
            1E
              3
            Thicken
            350
            21
              0
            DICTIONARY
              5
            6A
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbDictionary
            281
                 1
              3
            CTABLESTYLE
            350
            6B
              3
            DIMASSOC
            350
            6E
              3
            INDEXCTL
            350
            6D
              3
            SORTENTS
            350
            6C
              0
            XRECORD
              5
            81
            102
            {ACAD_REACTORS
            330
            C
            102
            }
            330
            C
            100
            AcDbXrecord
            280
                 1
              1
            DWGPROPS COOKIE
              2
            
              3
            
              4
            
              6
            
              7
            
              8
            三雄
              9
            
            300
            =
            301
            =
            302
            =
            303
            =
            304
            =
            305
            =
            306
            =
            307
            =
            308
            =
            309
            =
             40
            0.0014492592592593
             41
            2459198.769561898
             42
            2459198.771185336
              1
            
             90
                    0
              0
            LAYOUT
              5
            39
            102
            {ACAD_XDICTIONARY
            360
            86
            102
            }
            102
            {ACAD_REACTORS
            330
            2E
            102
            }
            330
            2E
            100
            AcDbPlotSettings
              1
            
              2
            Canon MG6200 series
              4
            
              6
            
             40
            0.0
             41
            0.0
             42
            0.0
             43
            0.0
             44
            0.0
             45
            0.0
             46
            0.0
             47
            0.0
             48
            0.0
             49
            0.0
            140
            0.0
            141
            0.0
            142
            1.0
            143
            1.0
             70
              1712
             72
                 0
             73
                 0
             74
                 0
              7
            
             75
                 0
            147
            1.0
            148
            0.0
            149
            0.0
            100
            AcDbLayout
              1
            Model
             70
                 1
             71
                 0
             10
            0.0
             20
            0.0
             11
            12.0
             21
            9.0
             12
            0.0
             22
            0.0
             32
            0.0
             14
            0.0
             24
            0.0
             34
            0.0
             15
            0.0
             25
            0.0
             35
            0.0
            146
            0.0
             13
            0.0
             23
            0.0
             33
            0.0
             16
            1.0
             26
            0.0
             36
            0.0
             17
            0.0
             27
            1.0
             37
            0.0
             76
                 0
            330
            36
            331
            3A
              0
            LAYOUT
              5
            35
            102
            {ACAD_XDICTIONARY
            360
            84
            102
            }
            102
            {ACAD_REACTORS
            330
            2E
            102
            }
            330
            2E
            100
            AcDbPlotSettings
              1
            
              2
            Canon MG6200 series
              4
            
              6
            
             40
            0.0
             41
            0.0
             42
            0.0
             43
            0.0
             44
            0.0
             45
            0.0
             46
            0.0
             47
            0.0
             48
            0.0
             49
            0.0
            140
            0.0
            141
            0.0
            142
            1.0
            143
            1.0
             70
               688
             72
                 0
             73
                 0
             74
                 5
              7
            
             75
                16
            147
            1.0
            148
            0.0
            149
            0.0
            100
            AcDbLayout
              1
            レイアウト1
             70
                 1
             71
                 1
             10
            0.0
             20
            0.0
             11
            12.0
             21
            9.0
             12
            0.0
             22
            0.0
             32
            0.0
             14
            1.000000000000000E+20
             24
            1.000000000000000E+20
             34
            1.000000000000000E+20
             15
            -1.000000000000000E+20
             25
            -1.000000000000000E+20
             35
            -1.000000000000000E+20
            146
            0.0
             13
            0.0
             23
            0.0
             33
            0.0
             16
            1.0
             26
            0.0
             36
            0.0
             17
            0.0
             27
            1.0
             37
            0.0
             76
                 0
            330
            32
              0
            MATERIAL
              5
            12
            102
            {ACAD_XDICTIONARY
            360
            72
            102
            }
            102
            {ACAD_REACTORS
            330
            10
            102
            }
            330
            10
            100
            AcDbMaterial
              1
            ByBlock
              0
            MATERIAL
              5
            11
            102
            {ACAD_XDICTIONARY
            360
            70
            102
            }
            102
            {ACAD_REACTORS
            330
            10
            102
            }
            330
            10
            100
            AcDbMaterial
              1
            ByLayer
              0
            MATERIAL
              5
            13
            102
            {ACAD_XDICTIONARY
            360
            74
            102
            }
            102
            {ACAD_REACTORS
            330
            10
            102
            }
            330
            10
            100
            AcDbMaterial
              1
            Global
              0
            MLINESTYLE
              5
            2C
            102
            {ACAD_REACTORS
            330
            2B
            102
            }
            330
            2B
            100
            AcDbMlineStyle
              2
            STANDARD
             70
                 0
              3
            
             62
               256
             51
            90.0
             52
            90.0
             71
                 2
             49
            0.5
             62
               256
              6
            BYLAYER
             49
            -0.5
             62
               256
              6
            BYLAYER
              0
            ACDBPLACEHOLDER
              5
            F
            102
            {ACAD_REACTORS
            330
            E
            102
            }
            330
            E
              0
            TABLESTYLE
              5
            31
            102
            {ACAD_XDICTIONARY
            360
            82
            102
            }
            102
            {ACAD_REACTORS
            330
            30
            102
            }
            330
            30
            100
            AcDbTableStyle
              3
            Standard
             70
                 0
             71
                 0
             40
            0.06
             41
            0.06
            280
                 0
            281
                 0
              7
            Standard
            140
            0.18
            170
                 2
             62
                 0
             63
                 7
            283
                 0
            274
                -2
            284
                 1
             64
                 0
            275
                -2
            285
                 1
             65
                 0
            276
                -2
            286
                 1
             66
                 0
            277
                -2
            287
                 1
             67
                 0
            278
                -2
            288
                 1
             68
                 0
            279
                -2
            289
                 1
             69
                 0
              7
            Standard
            140
            0.25
            170
                 5
             62
                 0
             63
                 7
            283
                 0
            274
                -2
            284
                 1
             64
                 0
            275
                -2
            285
                 1
             65
                 0
            276
                -2
            286
                 1
             66
                 0
            277
                -2
            287
                 1
             67
                 0
            278
                -2
            288
                 1
             68
                 0
            279
                -2
            289
                 1
             69
                 0
              7
            Standard
            140
            0.18
            170
                 5
             62
                 0
             63
                 7
            283
                 0
            274
                -2
            284
                 1
             64
                 0
            275
                -2
            285
                 1
             65
                 0
            276
                -2
            286
                 1
             66
                 0
            277
                -2
            287
                 1
             67
                 0
            278
                -2
            288
                 1
             68
                 0
            279
                -2
            289
                 1
             69
                 0
              0
            VISUALSTYLE
              5
            1A
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            2dWireframe
             70
                 4
             71
                 0
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    0
             66
               257
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 0
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            1C
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            3D Hidden
             70
                 6
             71
                 1
             72
                 2
             73
                 2
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 2
             91
                    2
             64
                 7
             65
               257
             75
                 2
            175
                 1
             42
            40.0
             92
                    0
             66
               257
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 3
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 0
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            1B
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            3dWireframe
             70
                 5
             71
                 0
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    0
             66
               257
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 0
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            19
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Basic
             70
                 7
             71
                 1
             72
                 0
             73
                 1
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 0
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            20
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Brighten
             70
                12
             71
                 2
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            50.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            24
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            ColorChange
             70
                16
             71
                 2
             72
                 2
             73
                 3
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 8
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 8
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            1D
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Conceptual
             70
                 9
             71
                 3
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 2
             91
                    2
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            40.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 3
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 0
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            1F
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Dim
             70
                11
             71
                 2
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            -50.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            23
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Facepattern
             70
                15
             71
                 2
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            15
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Flat
             70
                 0
             71
                 2
             72
                 1
             73
                 1
             90
                    2
             40
            -0.6
             41
            30.0
             62
                 5
             63
                 7
             74
                 0
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                   13
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            16
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            FlatWithEdges
             70
                 1
             71
                 2
             72
                 1
             73
                 1
             90
                    2
             40
            -0.6
             41
            30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    0
             66
               257
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                   13
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            17
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Gouraud
             70
                 2
             71
                 2
             72
                 2
             73
                 1
             90
                    2
             40
            -0.6
             41
            30.0
             62
                 5
             63
                 7
             74
                 0
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    0
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                   13
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            18
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            GouraudWithEdges
             70
                 3
             71
                 2
             72
                 2
             73
                 1
             90
                    2
             40
            -0.6
             41
            30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    0
             66
               257
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                   13
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            22
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Linepattern
             70
                14
             71
                 2
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 7
            175
                 7
             42
            1.0
             92
                    8
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            1E
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Realistic
             70
                 8
             71
                 2
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    0
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                    8
             66
                 8
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                   13
             44
            0.0
            173
                 0
            291
                 0
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            VISUALSTYLE
              5
            21
            102
            {ACAD_REACTORS
            330
            14
            102
            }
            330
            14
            100
            AcDbVisualStyle
              2
            Thicken
             70
                13
             71
                 2
             72
                 2
             73
                 0
             90
                    0
             40
            -0.6
             41
            -30.0
             62
                 5
             63
                 7
             74
                 1
             91
                    4
             64
                 7
             65
               257
             75
                 1
            175
                 1
             42
            1.0
             92
                   12
             66
                 7
             43
            1.0
             76
                 1
             77
                 6
             78
                 2
             67
                 7
             79
                 5
            170
                 0
            171
                 0
            290
                 0
            174
                 0
             93
                    1
             44
            0.0
            173
                 0
            291
                 1
             45
            0.0
            1001
            ACAD
            1000
            AcDbSavedByObjectVersion
            1070
                 0
            1000
            AcDbSavedByObjectVersion
            1070
                 0
              0
            DICTIONARYVAR
              5
            6B
            102
            {ACAD_REACTORS
            330
            6A
            102
            }
            330
            6A
            100
            DictionaryVariables
            280
                 0
              1
            STANDARD
              0
            DICTIONARYVAR
              5
            6E
            102
            {ACAD_REACTORS
            330
            6A
            102
            }
            330
            6A
            100
            DictionaryVariables
            280
                 0
              1
            1
              0
            DICTIONARYVAR
              5
            6D
            102
            {ACAD_REACTORS
            330
            6A
            102
            }
            330
            6A
            100
            DictionaryVariables
            280
                 0
              1
            0
              0
            DICTIONARYVAR
              5
            6C
            102
            {ACAD_REACTORS
            330
            6A
            102
            }
            330
            6A
            100
            DictionaryVariables
            280
                 0
              1
            127
              0
            DICTIONARY
              5
            86
            330
            39
            100
            AcDbDictionary
            280
                 1
            281
                 1
              3
            ACAD_XREC_ROUNDTRIP
            360
            87
              0
            DICTIONARY
              5
            84
            330
            35
            100
            AcDbDictionary
            280
                 1
            281
                 1
              3
            ACAD_XREC_ROUNDTRIP
            360
            85
              0
            DICTIONARY
              5
            72
            330
            12
            100
            AcDbDictionary
            280
                 1
            281
                 1
              3
            ACAD_XREC_ROUNDTRIP
            360
            73
              0
            DICTIONARY
              5
            70
            330
            11
            100
            AcDbDictionary
            280
                 1
            281
                 1
              3
            ACAD_XREC_ROUNDTRIP
            360
            71
              0
            DICTIONARY
              5
            74
            330
            13
            100
            AcDbDictionary
            280
                 1
            281
                 1
              3
            ACAD_XREC_ROUNDTRIP
            360
            75
              0
            DICTIONARY
              5
            82
            330
            31
            100
            AcDbDictionary
            280
                 1
            281
                 1
              3
            ACAD_XREC_ROUNDTRIP
            360
            83
              0
            XRECORD
              5
            87
            102
            {ACAD_REACTORS
            330
            86
            102
            }
            330
            86
            100
            AcDbXrecord
            280
                 1
            102
            SHADEPLOT
             70
                 0
            102
            SHADEPLOTRESLEVEL
             70
                 2
            102
            SHADEPLOTCUSTOMDPI
             70
               300
              0
            XRECORD
              5
            85
            102
            {ACAD_REACTORS
            330
            84
            102
            }
            330
            84
            100
            AcDbXrecord
            280
                 1
            102
            SHADEPLOT
             70
                 0
            102
            SHADEPLOTRESLEVEL
             70
                 2
            102
            SHADEPLOTCUSTOMDPI
             70
               300
              0
            XRECORD
              5
            73
            102
            {ACAD_REACTORS
            330
            72
            102
            }
            330
            72
            100
            AcDbXrecord
            280
                 1
            102
            MATERIAL
            148
            0.0
            149
            0.0
            149
            0.0
             93
                    0
             94
                   63
            282
                 0
             72
                 1
             77
                 1
            171
                 1
            175
                 1
            179
                 1
            273
                 0
              0
            XRECORD
              5
            71
            102
            {ACAD_REACTORS
            330
            70
            102
            }
            330
            70
            100
            AcDbXrecord
            280
                 1
            102
            MATERIAL
            148
            0.0
            149
            0.0
            149
            0.0
             93
                    0
             94
                   63
            282
                 0
             72
                 1
             77
                 1
            171
                 1
            175
                 1
            179
                 1
            273
                 0
              0
            XRECORD
              5
            75
            102
            {ACAD_REACTORS
            330
            74
            102
            }
            330
            74
            100
            AcDbXrecord
            280
                 1
            102
            MATERIAL
            148
            0.0
            149
            0.0
            149
            0.0
             93
                    0
             94
                   63
            282
                 0
             72
                 1
             77
                 1
            171
                 1
            175
                 1
            179
                 1
            273
                 0
              0
            XRECORD
              5
            83
            102
            {ACAD_REACTORS
            330
            82
            102
            }
            330
            82
            100
            AcDbXrecord
            280
                 1
            102
            ACAD_ROUNDTRIP_PRE2007_TABLESTYLE
             90
                  512
             91
                    0
              1
            
             92
                  512
             93
                    0
              2
            
             94
                  512
             95
                    0
              3
            
              0
            ENDSEC
            0
            EOF
        """.trimIndent())
        writer_.newLine()
    }

    override fun PolymorphFunction(): String {
        return super.PolymorphFunction()
    }

    override fun PolymorphFunctionB(): String {
        return "IAMOVERRIDED."
    }

}